version: '3.8'
services:
  # app:
    # build:
    #   context: . # Context should only operate on a File System context based on the root directory
    #   target: dev
    # # image: node:18-alpine
    # # working_dir: /app
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    # volumes:
    #   - ./:/app
    #   - D:/DataWorkspaces/stream-assist-bot/logs:/app/logs
    #   - D:/DataWorkspaces/stream-assist-bot/cache/:/app/local-cache/
  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - stream-assist-bot-database:/var/lib/postgresql/data
      # - D:\\DataWorkspaces\\stream-assist-bot\\database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: stream-assist-bot
      POSTGRES_PASSWORD: Vsnyi&FN^oLXUVqdjm9v4
    ports:
      - '6432:5432' # Expose the default postgres port
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  stream-assist-bot-database:
