{{
    const scopes = [
        "analytics:read:games",
        "bits:read",
        "channel:manage:broadcast",
        "channel:manage:redemptions",
        "channel:moderate",
        "channel:read:hype_train",
        "channel:read:redemptions",
        "channel:read:subscriptions",
        "chat:edit",
        "chat:read",
        "moderation:read",
        "moderator:manage:announcements",
        "moderator:read:followers",
        "user:read:follows",
        "user:read:subscriptions"
    ]
    exports.scopes = scopes.join(' ')
}}

# @scopes_encoded = {{scopes.join(' ')}}
# @scopes_encoded = {{$join scopes ' '}}
@nonce = {{$guid}}

### Authorization Code Grant Flow
# @name = openInBrowser
# @plugin = open
GET https://id.twitch.tv/oauth2/authorize
    ?response_type=code
    &client_id={{TWITCH_APP_CLIENT_ID}}
    &redirect_uri=http://localhost
    &state={{nonce}}
    &scope={{scopes}}

###

# ### Get Stream Info
# GET https://api.twitch.tv/helix/streams?user_id=<user_id>
# Authorization: Bearer <access_token>
# Client-Id: <client_id>

# http://localhost/?code=2n85ngr03eilhah8xafmsuz9ahxe4u&scope=analytics%3Aread%3Agames+bits%3Aread+channel%3Amanage%3Abroadcast+channel%3Amanage%3Aredemptions+channel%3Amoderate+channel%3Aread%3Ahype_train+channel%3Aread%3Aredemptions+channel%3Aread%3Asubscriptions+chat%3Aedit+chat%3Aread+moderation%3Aread+moderator%3Amanage%3Aannouncements+moderator%3Aread%3Afollowers+user%3Aread%3Afollows+user%3Aread%3Asubscriptions&state=b9b8f177-d965-4665-b75e-31587b0e08c1


### Autehntication Token Request
POST https://id.twitch.tv/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id={{TWITCH_APP_CLIENT_ID}}
&client_secret={{TWITCH_APP_CLIENT_SECRET}}
&code=iua8uqa95cbko5jss2lxhqa5bygt93
&grant_type=authorization_code
&redirect_uri=http://localhost

###
GET https://api.twitch.tv/helix/users?login=timy_bot
Authorization: Bearer 4l9hhzsrk25ms8u2i0w1woaowkzj8z
Client-Id: {{TWITCH_APP_CLIENT_ID}}


###