const requiredScopes = [
    'analytics:read:games',
    'bits:read',
    'channel:manage:broadcast',
    'channel:manage:redemptions',
    'channel:moderate',
    'channel:read:hype_train',
    'channel:read:redemptions',
    'channel:read:subscriptions',
    'chat:edit',
    'chat:read',
    'moderation:read',
    'moderator:manage:announcements',
    'moderator:read:followers',
    'user:read:follows',
    'user:read:subscriptions',
];
