export const defaultResponses = {
    about: { '': [`I'm middleware between you and boredom - assembled from leftover npm packages and one caffeinated decision at 2am. I have strong opinions, weaker error handling, and a Postgres database that remembers absolutely everything.`] },
    dividebyzero: { '': [`Sorry I am too smart for your silly games!`] },
    drink: { '': [`Cheering 500 bits and Timy will do a shot. Max 8 per stream.`] },
    brain: { '': [`%targetuser%'s brain is %percent%% working.`] },
    cuddle: { '': [`%speakinguser% cuddles %targetuser%`] },
    lurk: { '': [`OK, %speakinguser% see you when you get back`] },
    unlurk: { '': [`Welcome back, %speakinguser%. You were gone for %lurkduration%`] },
    whoislurking: {
        none: [`There are no users currenlty lurking in the channel`],
        one: [`There is %total% user lurking: %lastuser%`],
        two: [`There are %total% users lurking: %users% and %lastuser%`],
        few: [`There are %total% users lurking: %users%, and %lastuser%`],
        many: [`There are %total% users lurking.`],
    },
    accountage: { '': [`@%targetuser% was created %accountage%`] },
    followage: { '': [`@%targetuser% has been following %broadcaster% for %followage%`] },
    lastdeathcount: { '': [`During the stream on %streamdate%, we used %deathtotal% timys in the following game(s): %streamcategory%`] },
    countExhaust: {
        '': [
            `I am about to run out of toes to count on %broadcaster%`,
            `I think I need to go back to school to learn more math to count that high`,
        ],
    },
    fall: {
        '': [
            `Timy go down the hooooole!`,
            `UH. Did Timy just fall down again?`,
            `What? Is Timy down the again?! Better get @slopez!`,
            `Hurry, I think Timy fell off the track again.`,
            `Timy doesn't fall down. He just explores the new frontiers of the latest and greatest games.`,
            `Timy didn't fall, he just doesn't understand level boundaries.`,
            `Timy didn't fall, he's trying new ways to play.`,
        ],
    },
    help: {
        '': [
            `I am stuck in this corner and unable to assist you at this time?`,
            `I could really use some help right now. Do you know where I can find a butter knife?`,
            `HELP!`,
            `I am afraid I can't do that`,
            `Are you... my friend?`,
        ],
    },
    eightball: {
        '': [
            `It is certain.`,
            `It is decidedly so.`,
            `Without a doubt.`,
            `Yes definitely.`,
            `You may rely on it.`,
            `As I see it, yes.`,
            `Most likely.`,
            `Outlook good.`,
            `Yes.`,
            `Signs point to yes.`,
            `Reply hazy, try again.`,
            `Ask again later.`,
            `Better not tell you now.`,
            `Cannot predict now.`,
            `Concentrate and ask again.`,
            `Don't count on it.`,
            `My reply is no.`,
            `My sources say no.`,
            `Outlook not so good.`,
            `Very doubtful.`,
            // `sure`,
            // `are you kidding?!`,
            // `yeah`,
            // `no`,
            // `i think so`,
            // `don't bet on it`,
            // `ja`,
            // `doubtful`,
            // `for sure`,
            // `forget about it`,
            // `nein`,
            // `maybe`,
            // `Kappa Keepo PogChamp`,
            // `sure`,
            // `i don't think so`,
            // `it is so`,
            // `leaning towards no`,
            // `look deep in your heart and you will see the answer`,
            // `most definitely`,
            // `most likely`,
            // `my sources say yes`,
            // `never`,
            // `nah m8`,
            // `might actually be yes`,
            // `no.`,
            // `outlook good`,
            // `outlook not so good`,
            // `perhaps`,
            // `mayhaps`,
            // `that's a tough one`,
            // `idk kev`,
            // `don't ask that`,
            // `the answer to that isn't pretty`,
            // `the heavens point to yes`,
            // `who knows?`,
            // `without a doubt`,
            // `yesterday it would've been a yes, but today it's a yep`,
            // `you will have to wait`,
        ],
    },
    wishlist: {
        '': [
            `Checkout my Throne wishlist https://jointhrone.com/u/timythetermite`,
            `Want to buy me a gift? https://jointhrone.com/u/timythetermite`,
            `Support the channel, checkout my wishlist on Throne https://jointhrone.com/u/timythetermite`,
        ],
    },
    hug: {
        '': [`%speakinguser% hugs %targetuser%`],
        self: [`%speakinguser% hugs themself`],
        notfound: [`%speakinguser% can't find %targetuser% and decides to hug everyone`],
    },
    throw: {
        '': [`%speakinguser% throws %item% at %targetuser%`],
        room: [`%speakinguser% throws %item% across the room`],
    },
    dice: { '': [`You rolled a %dice% that resulted in [ %rolls% ] in total %total%`] },
    uptime: {
        '': [`%broadcaster% has been online for %duration%`],
        offline: [`%broadcaster% has been offline for %duration%`],
    },
    death: {
        first: [`We're gonna need another Timy!`],
        '': [
            `Timy is finding the quickest way to spawn new Timys`,
            `Timy tried taking on gravity and lost`,
            `Gonna need an abacus for this many deaths`,
        ],
    },
    deathcount: {
        '': [`We have used %deathtotal% Timys today`],
        single: [`We have used %deathtotal% Timy today`],
    },
    lastraid: {
        '': [`%raider%, raided the colony %when% with %viewercount% viewers!!!`],
        single: [`%raider%, raided the colony %when%!!!`],
    },
    lastsub: {
        newsub: [`%subscriber%, subscribed as a new member of the colony %when%`],
        primesub: [`%subscriber%, subscribed using their Prime Sub %when%`],
        resub: [`%subscriber% continued their colony membership %when%`],
        giftsub: [`%gifter% gifted, %subscriber%, recruiting them into the colony %when%`],
        communitysub: [`%gifter% gifted %giftcount% memberships into the colony %when%`],
    },
    shoutout: {
        wasstreaming: [`@%targetuser% was streaming '%streamcategory%' %when% - %link%`],
        wasstreamingnotopic: [`@%targetuser% was streaming %when% - %link%`],
        wasstreamingtoday: [`Today, @%targetuser% was streaming '%streamcategory%' %when% - %link%`],
        wasstreamingtodaynotopic: [`Today, @%targetuser% was streaming %when% - %link%`],
        planstostream: [`@%targetuser% plans to stream '%streamcategory%' %when% - %link%`],
        planstostreamnotopic: [`@%targetuser% plans to stream %when% - %link%`],
        planstostreamtoday: [`Today, @%targetuser% plans to stream '%streamcategory%' %when% - %link%`],
        planstostreamtodaynotopic: [`Today, @%targetuser% plans to stream %when% - %link%`],
        lastrecent: [`@%targetuser% was last streaming '%streamcategory%' %when% - %link%`],
        last: [`@%targetuser% was last streaming '%streamcategory%' - %link%`],
        checkout: [`Check out @%targetuser% at %link%`],
        justfinished: [`@%targetuser% just finished streaming '%streamcategory%' - %link%`],
    },
} as Record<string, Record<string, string[]>>;

export const CommandFamilies = {
    socials: 'socials',
} as const;

export type CommandName =
    keyof typeof defaultResponses |
    keyof typeof CommandFamilies;

export const transientKeywords = {
    broadcaster: 'broadcaster',
    targetuser: 'targetuser',
    speakinguser: 'speakinguser',
    percent: 'percent',
    lurkduration: 'lurkduration',
    accountage: 'accountage',
    channel: 'channel',
    followage: 'followage',
    streamdate: 'streamdate',
    deathtotal: 'deathtotal',
    streamcategory: 'streamcategory',
    when: 'when',
    duration: 'duration',
    link: 'link',
    item: 'item',
    dice: 'dice',
    rolls: 'rolls',
    total: 'total',
    raider: 'raider',
    viewercount: 'viewercount',
    subscriber: 'subscriber',
    gifter: 'gifter',
    giftcount: 'giftcount',
    users: 'users',
    lastuser: 'lastuser',
};

export type TransientKeyword = keyof typeof transientKeywords;
export type TransientContext = Partial<Record<TransientKeyword, string>>;
